import os
import subprocess
from groq import Groq
from github import Github

# 1. Initialize Clients
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
gh = Github(os.getenv("GITHUB_TOKEN")) # Provided automatically by GitHub Actions

REPO = os.getenv("GITHUB_REPOSITORY")
PR_NUMBER = int(os.getenv("PR_NUMBER"))

def get_diff():
    """Get the git diff of the PR."""
    # Fetch the PR branch and diff against main/master
    subprocess.run(["git", "fetch", "origin", f"pull/{PR_NUMBER}/head:pr-branch"], check=True)
    result = subprocess.run(
        ["git", "diff", "origin/main...pr-branch"], # Adjust 'main' to 'master' if needed
        capture_output=True, text=True
    )
    return result.stdout[:15000] # Truncate to avoid token limits (15k chars ~ 4k tokens)

def run_agent(prompt_file: str, diff: str, agent_name: str) -> str:
    """Send diff to Groq for analysis."""
    with open(f"prompts/{prompt_file}", "r") as f:
        system_prompt = f.read()
    
    response = groq_client.chat.completions.create(
        model="llama3-70b-8192", # Free, fast, and highly capable
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Review this diff:\n\n```diff\n{diff}\n```"}
        ],
        temperature=0.2,
        max_tokens=1000
    )
    return response.choices[0].message.content

def main():
    print(f"🔍 Starting AI Review for PR #{PR_NUMBER}")
    diff = get_diff()
    
    if not diff.strip():
        print("✅ No code changes to review.")
        return

    # Run agents sequentially (fast enough with Groq)
    security_result = run_agent("security.txt", diff, "Security")
    performance_result = run_agent("performance.txt", diff, "Performance")
    quality_result = run_agent("quality.txt", diff, "Quality")

    # Format the final comment
    comment = f"""# 🤖 AI Code Review (Serverless & Free)

### 🔒 Security
{security_result}

### ⚡ Performance
{performance_result}

### ✨ Quality
{quality_result}

---
*Generated by GitHub Actions + Groq (Llama 3 70B)*
"""

    # Post to GitHub PR
    repo = gh.get_repo(REPO)
    pr = repo.get_pull(PR_NUMBER)
    pr.create_issue_comment(comment)
    print("✅ Review posted successfully!")

if __name__ == "__main__":
    main()